# Generated by Django 5.0.3 on 2024-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0002_alter_complaint_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=2083, null=True),
        ),
    ]
